# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Automation Academy

on:
  push:
    branches: [ browserstack_connection ]

jobs:
  build:
    name: 'BrowserStack Test'
    runs-on: windows-latest
    env:
          BROWSER: ${{ secrets.BROWSER }}
          BROWSER_VERSION: ${{ secrets.BROWSER_VERSION }}
          ENVIRONMENT: ${{ secrets.ENVIRONMENT }}
          EXECUTION: ${{ secrets.EXECUTION }}
          IS_CI_EXECUTION: ${{ secrets.IS_CI_EXECUTION }}
          OS_NAME: ${{ secrets.OS_NAME }}
          OS_VERSION: ${{ secrets.OS_VERSION }}
          PARALLEL_EXECUTION: ${{ secrets.PARALLEL_EXECUTION }}
    steps:
      - name: 'BrowserStack Env Setup'  # Invokes the setup-env action
        uses: browserstack/github-actions/setup-env@master
        with:
          username:  ${{ secrets.BROWSERSTACK_USERNAME }}
          access-key: ${{ secrets.BROWSERSTACK_ACCESS_KEY }}
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run test
        run: |
          behave
                
