# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Automation Academy

on:
  push:
    branches: [ master ]

jobs:
  build:
    name: 'Saucelabs Test'
    runs-on: windows-latest
    env:
          platformName: ${{ secrets.PLATFORMNAME }}
          platformVersion: ${{ secrets.PLATFORMVERSION }}
          appiumVersion: ${{ secrets.APPIUMVERSION }}
          deviceName: ${{ secrets.DEVICENAME }}
          browserName: ${{ secrets.BROWSERNAME }}
          ENVIRONMENT: ${{ secrets.ENVIRONMENT }}
          EXECUTION: ${{ secrets.EXECUTION }}
          name: ${{ secrets.NAME }}
          build: ${{ secrets.BUILD }}
          IS_CI_EXECUTION: ${{ secrets.IS_CI_EXECUTION }}
          SAUCELABS_USERNAME: ${{secrets.SAUCELABS_USERNAME}}
          SAUCELABS_ACCESS_KEY: ${{secrets.SAUCELABS_ACCESS_KEY}}
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run test
        run: |
          behave
